# See: https://github.com/oss-review-toolkit/ort/blob/main/docs/config-file-ort-yml.md
analyzer:
  skip_excluded: true
excludes:
  paths:
    - pattern: ".github/**"
      reason: "BUILD_TOOL_OF"
      comment: "Github Action Definitions"
    - pattern: ".idea/**"
      reason: "OTHER"
      comment: "IDE Config for Idea"
    - pattern: ".vscode/**"
      reason: "OTHER"
      comment: "IDE Config vor VSCode"
    - pattern: "docs/**"
      reason: "DOCUMENTATION_OF"
    - pattern: "scripts/**"
      reason: "BUILD_TOOL_OF"
      comment: "Used for Deployment"
    - pattern: "examples/**"
      reason: "EXAMPLE_OF"
      comment: "Example Projects"
  scopes:
    - pattern: "devDependencies"
      reason: "DEV_DEPENDENCY_OF"
      comment: "Packages for development only."
